---
- name: Install sendmail package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - sendmail-bin
    - sendmail

- name: Enable sendmail service
  service:
    name: sendmail
    enabled: yes
