---
- name: Update system
  apt:
    update_cache: yes
    upgrade: dist

- name: Install packages (unattended-upgrades, update-notifier-common)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unattended-upgrades
    - update-notifier-common

- name: Setup auto upgrades
  template:
    src: etc/apt/apt.conf.d/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Setup unattended upgrades
  template:
    src: etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
