---
docker_version: '5:18.09.0~3-0~ubuntu-xenial'
docker_apt_release_channel: 'stable'
docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'
docker_group_members:
  - "{{ lookup('env', 'HOST_USERNAME') }}"
